service: wepool-apollo-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  graphql:
    handler: src/graphql-api/apollo-server.graphqlServer
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  auth:
    handler: src/api/auth/auth.authHandler
    events:
      - http:
          path: auth
          method: post
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true
    packager: npm
    webpackConfig: webpack.config.js
